// <auto-generated />
namespace MySql_SqLite_Synchronization.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedDTO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedDTO));
        
        string IMigrationMetadata.Id
        {
            get { return "201612262254067_AddedDTO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
